#!/bin/sh

sudo -u gdm gconftool-2 --set --type string --set /desktop/gnome/interface/gtk_theme FurryLogin
sudo -u gdm gconftool-2 --set --type string --set /desktop/gnome/interface/icon_theme FurryLoginIcons
